name: Test

on:
  push:
    branches: [ main ]
  pull_request: 

env:
  # Disable the .NET logo in the console output.
  DOTNET_NOLOGO: true
  # Disable the .NET first time experience to skip caching NuGet packages and speed up the build.
  DOTNET_SKIP_FIRST_TIME_EXPERIENCE: true
  # Disable sending .NET CLI telemetry to Microsoft.
  DOTNET_CLI_TELEMETRY_OPTOUT: true

jobs:
  build:
    name: Build ${{matrix.os}}
    runs-on: ${{matrix.os}}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, windows-latest, windows-latest]
      fail-fast: false
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: NuGet Locals
      run: nuget locals all -list
    - name: NuGet Home Folder (if available)
      run: ls -la ~/.nuget
      if: always()
      shell: bash
    - name: Default NuGet.Config (if available)
      run: cat ~/.nuget/NuGet/NuGet.Config
      if: always()
      shell: bash
    - name: Global NuGet Packages (if available)
      run: ls -la ~/.nuget/packages
      if: always()
      shell: bash
    - name: .NET Restore
      run: dotnet restore --verbosity detailed
      if: always()
